### ISSUE TITLE
Error when insert data into table with trigger enabled:

### ISSUE THREAD

**Issue by hwwan80** [rails-sqlserver/activerecord-sqlserver-adapter#339]
After i upgrade to 4.0.0, the following error exception occured when inserting data to a table :+1: 

```ruby
ActiveRecord::StatementInvalid (TinyTds::Error: The target table 'tableName' of the DML statement cannot have any enabled triggers if the
statement contains an OUTPUT clause without INTO clause.: EXEC sp_executesql N'INSERT INTO [tableName] ([column1], [column2]) OUTPUT inserted.primaryKeyColumn VALUES (@0, @1)', N'@0 varchar(200), @1 tinyint, @0 = N'Unit Testing', @1 = 23):
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:419:in `each'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:419:in `handle_to_names_and_values_dblib'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:408:in `handle_to_names_and_values'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:381:in `_raw_select'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:376:in `block in raw_select'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
  activesupport (4.0.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:376:in `raw_select'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:359:in `do_exec_query'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:24:in `exec_query'
  activerecord-sqlserver-adapter (4.0.0) lib/active_record/connection_adapters/sqlserver/database_statements.rb:30:in `exec_insert'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract/database_statements.rb:107:in `insert'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
  activerecord (4.0.5) lib/active_record/relation.rb:76:in `insert'
  activerecord (4.0.5) lib/active_record/persistence.rb:510:in `create_record'
  activerecord (4.0.5) lib/active_record/attribute_methods/dirty.rb:78:in `create_record'
  activerecord (4.0.5) lib/active_record/callbacks.rb:306:in `block in create_record'
  activesupport (4.0.5) lib/active_support/callbacks.rb:373:in `_run__329301003__create__callbacks'
  activesupport (4.0.5) lib/active_support/callbacks.rb:80:in `run_callbacks'
  activerecord (4.0.5) lib/active_record/callbacks.rb:306:in `create_record'
  activerecord (4.0.5) lib/active_record/timestamp.rb:57:in `create_record'
  activerecord (4.0.5) lib/active_record/persistence.rb:478:in `create_or_update'
  activerecord (4.0.5) lib/active_record/callbacks.rb:302:in `block in create_or_update'
  activesupport (4.0.5) lib/active_support/callbacks.rb:413:in `_run__329301003__save__callbacks'
  activesupport (4.0.5) lib/active_support/callbacks.rb:80:in `run_callbacks'
  activerecord (4.0.5) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.0.5) lib/active_record/persistence.rb:103:in `save'
  activerecord (4.0.5) lib/active_record/validations.rb:51:in `save'
  activerecord (4.0.5) lib/active_record/attribute_methods/dirty.rb:32:in `save'
  activerecord (4.0.5) lib/active_record/transactions.rb:270:in `block (2 levels) in save'
  activerecord (4.0.5) lib/active_record/transactions.rb:330:in `block in with_transaction_returning_status'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract/database_statements.rb:221:in `within_new_transaction'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.0.5) lib/active_record/transactions.rb:209:in `transaction'
  activerecord (4.0.5) lib/active_record/transactions.rb:327:in `with_transaction_returning_status'
  activerecord (4.0.5) lib/active_record/transactions.rb:270:in `block in save'
  activerecord (4.0.5) lib/active_record/transactions.rb:285:in `rollback_active_record_state!'
  activerecord (4.0.5) lib/active_record/transactions.rb:269:in `save'

```

tableName have trigger enabled.

The application do something like:

```ruby
@model = Model.new(model_params)
@model.build_collection(collection_params)
@model.save
````

**Comment by metaskills** [comment]
I have created issue #381and I want to solve this for v4.2.1. Please watch that ticket and provide feedback/advice if you are about this issue. Cheers.

**Comment by bergpb** [comment]
After try a insert in table i get this error:
TinyTds::Error: The target table 'table_name' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
Can anyone help me to fix this?
