### ISSUE TITLE
upgrade to rails 4.2.0

### ISSUE THREAD

**Issue by diospi** [rails-sqlserver/activerecord-sqlserver-adapter#367]
I tried to make a update on rails 4.2.0.rc2 and I get an error accessing my mssql-database. In my application I only run a query on mssql and I get the following error trace:
```
activerecord (4.2.0.rc2) lib/active_record/attribute_methods/time_zone_conversion.rb:60:in `create_time_zone_conversion_attribute?'
activerecord (4.2.0.rc2) lib/active_record/attribute_methods/time_zone_conversion.rb:49:in `block (2 levels) in inherited'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:61:in `call'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:61:in `block in matching'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:60:in `select'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:60:in `matching'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:56:in `decorators_for'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:47:in `apply'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:29:in `block in add_user_provided_columns'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:28:in `map'
activerecord (4.2.0.rc2) lib/active_record/attribute_decorators.rb:28:in `add_user_provided_columns'
activerecord (4.2.0.rc2) lib/active_record/attributes.rb:91:in `columns'
activerecord (4.2.0.rc2) lib/active_record/attributes.rb:96:in `columns_hash'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:968:in `block in create_binds'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:965:in `each'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:965:in `partition'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:965:in `create_binds'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:952:in `build_where'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:584:in `where!'
activerecord (4.2.0.rc2) lib/active_record/relation/query_methods.rb:574:in `where'
activerecord (4.2.0.rc2) lib/active_record/querying.rb:10:in `where'
actionpack (4.2.0.rc2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.0.rc2) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.0.rc2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.0.rc2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0.rc2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.0.rc2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.0.rc2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.2.0.rc2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0.rc2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0.rc2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.0.rc2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.0.rc2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.0.rc2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.0.rc2) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.0.rc2) lib/action_view/rendering.rb:30:in `process'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiling_methods.rb:108:in `block in profile_method'
actionpack (4.2.0.rc2) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.2.0.rc2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.0.rc2) lib/action_controller/metal.rb:236:in `block in action'
actionpack (4.2.0.rc2) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (4.2.0.rc2) lib/action_dispatch/routing/route_set.rb:42:in `serve'
actionpack (4.2.0.rc2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.0.rc2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.0.rc2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.0.rc2) lib/action_dispatch/routing/route_set.rb:802:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.0.beta2) lib/rack/etag.rb:24:in `call'
rack (1.6.0.beta2) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.0.beta2) lib/rack/head.rb:13:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.0.beta2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.0.beta2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.0.rc2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.0.rc2) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0.rc2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0.rc2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0.rc2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0.rc2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0.rc2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.0.beta2) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.0.beta2) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.0.beta2) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0.rc2) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.0.beta2) lib/rack/sendfile.rb:113:in `call'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiler.rb:300:in `call'
railties (4.2.0.rc2) lib/rails/engine.rb:518:in `call'
railties (4.2.0.rc2) lib/rails/application.rb:164:in `call'
rack (1.6.0.beta2) lib/rack/lock.rb:17:in `call'
rack (1.6.0.beta2) lib/rack/content_length.rb:15:in `call'
rack (1.6.0.beta2) lib/rack/handler/webrick.rb:89:in `service'
```

thanks in advance!

**Comment by marcomd** [comment]
+1
I'd like to try it with rails 4.2

**Comment by metaskills** [comment]
Closing this issue. I am working on Rails 4.2 in master now. Master will be completely broken for a few weeks while I move to the new Type interfaces and an updated Arel visitor.

**Comment by plainprogrammer** [comment]
Do you have any specific open issues tied to Rails 4.2 support or any areas you'd like someone else to do?

**Comment by metaskills** [comment]
Right now it's a solo job till I get the new foundation done. Thanks for the offer. I plan to make a comprehensive post and note some areas that could be better or may need help in a week or so.

**Comment by lustrousgorilla** [comment]
Thanks for working on this! We're looking forward to 4.2 support.

**Comment by ume3119** [comment]
I am facing the same issue for rails 4.2.8.
Was it fixed for Rails 2?
