### ISSUE TITLE
update_attributes with accepts_nested_attributes fails

### ISSUE THREAD

**Issue by jwoertink** [rails-sqlserver/activerecord-sqlserver-adapter#372]
I have these two models.
```ruby
class Appointment < ActiveRecord::Base
  self.table_name = "Appointment"
  has_one :appointment_visitor, foreign_key: 'appointmentid'
  accepts_nested_attributes_for :appointment_visitor
end

class AppointmentVisitor < ActiveRecord::Base
  self.table_name = "AppointmentVisitor"
  belongs_to :appointment, foreign_key: 'appointmentid'
end
```

When I use create, everything works fine.
```ruby
# this creates the appointment and appointment_visitor with association
Appointment.create(rowid: guid, appointment_visitor_attributes: av_params)
```

When I try to update them using `update_attributes`, it fails with a foreign key null error

```ruby
@appointment = Appointment.find(params[:id])
# this fails because it says that AppointmentId in the AppointmentVisitor table is null
@appointment.update_attributes({rowid: guid, appointment_visitor_attributes: av_params})
```

```text
[10] pry(Appointment)> appointment
=> #<Appointment id: 52, rowstateid: 1, summary: nil, description: "When: Thursday, January 22, 2015  9:08 AM. (UTC-08...", employeeid: 273863, startdate: "2015-01-22 17:08:42", enddate: "2015-01-22 17:08:42", location: "Casapiedra", icaluid: "1234ASDF", icalsequence: 0, iscanceled: false, rowid: "9DEA7AA3-348E-4C32-A723-109D3BC20207">
[11] pry(Appointment)> appointment.update_attributes(appointment_visitor_attributes: params.merge(checkedinat: Time.now))
  SQL (1.6ms)  BEGIN TRANSACTION
  SQL (5.1ms)  EXEC sp_executesql N'UPDATE [AppointmentVisitor] SET [appointmentid] = @0 WHERE [AppointmentVisitor].[id] = 10052; SELECT @@ROWCOUNT AS AffectedRows', N'@0 bigint', @0 = NULL  [["appointmentid", nil]]
TinyTds::Error: Cannot insert the value NULL into column 'AppointmentId', table 'Alice_Test_Asura.dbo.AppointmentVisitor'; column does not allow nulls. UPDATE fails.: EXEC sp_executesql N'UPDATE [AppointmentVisitor] SET [appointmentid] = @0 WHERE [AppointmentVisitor].[id] = 10052; SELECT @@ROWCOUNT AS AffectedRows', N'@0 bigint', @0 = NULL
  SQL (1.3ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'AppointmentId', table 'Alice_Test_Asura.dbo.AppointmentVisitor'; column does not allow nulls. UPDATE fails.: EXEC sp_executesql N'UPDATE [AppointmentVisitor] SET [appointmentid] = @0 WHERE [AppointmentVisitor].[id] = 10052; SELECT @@ROWCOUNT AS AffectedRows', N'@0 bigint', @0 = NULL
from /Users/jeremy/.rvm/gems/ruby-2.1.5@ard-checkin/gems/activerecord-sqlserver-adapter-4.1.0/lib/active_record/connection_adapters/sqlserver/database_statements.rb:423:in `each'
[12] pry(Appointment)> appointment.appointment_visitor
=> #<AppointmentVisitor id: 10052, rowstateid: 1, appointmentid: nil, title: nil, firstname: "Selmer", middlename: nil, lastname: "Pagac", suffix: nil, displayname: nil, phonenumber: nil, organizationname: nil, email: "mckenzie@brakus.co.uk", checkedinat: nil, checkedoutat: nil>
[13] pry(Appointment)> av
=> #<AppointmentVisitor id: 10052, rowstateid: 1, appointmentid: 52, title: nil, firstname: "Selmer", middlename: nil, lastname: "Pagac", suffix: nil, displayname: nil, phonenumber: nil, organizationname: nil, email: "mckenzie@brakus.co.uk", checkedinat: nil, checkedoutat: nil>
```

I'm not sure why it wants to set the appointmentid to nil, but I'm not familiar with SQL Server, or this gem so I may just have something setup wrong too.

**Comment by metaskills** [comment]
Can you try the latest v4.2.0.pre version?
http://metaskills.net/2015/01/25/activerecord-sqlserver-v4.2.0---code-name-kantishna/

**Comment by jwoertink** [comment]
Updated to rails 4.2.0 and ASA 4.2.0.pre, and I still get the same error.
```text
[5] pry(Appointment)> appointment.update_attributes(directoryid: directoryid, appointment_visitor_attributes: params.merge(checkedinat: Time.current))
  SQL (1.8ms)  BEGIN TRANSACTION
  AppointmentVisitor Load (5.4ms)  EXEC sp_executesql N'SELECT  [AppointmentVisitor].* FROM [AppointmentVisitor] WHERE [AppointmentVisitor].[appointmentid] = @0  ORDER BY [AppointmentVisitor].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY', N'@0 bigint', @0 = 59  [["appointmentid", 59]]
  SQL (8.7ms)  EXEC sp_executesql N'UPDATE [AppointmentVisitor] SET [appointmentid] = @0 WHERE [AppointmentVisitor].[id] = @1; SELECT @@ROWCOUNT AS AffectedRows', N'@0 bigint, @1 bigint', @0 = NULL, @1 = 10059  [["appointmentid", nil], ["id", 10059]]
TinyTds::Error: Cannot insert the value NULL into column 'AppointmentId', table 'Alice_Test_Asura.dbo.AppointmentVisitor'; column does not allow nulls. UPDATE fails.: EXEC sp_executesql N'UPDATE [AppointmentVisitor] SET [appointmentid] = @0 WHERE [AppointmentVisitor].[id] = @1; SELECT @@ROWCOUNT AS AffectedRows', N'@0 bigint, @1 bigint', @0 = NULL, @1 = 10059
  SQL (2.0ms)  ROLLBACK TRANSACTION
ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'AppointmentId', table 'Alice_Test_Asura.dbo.AppointmentVisitor'; column does not allow nulls. UPDATE fails.: EXEC sp_executesql N'UPDATE [AppointmentVisitor] SET [appointmentid] = @0 WHERE [AppointmentVisitor].[id] = @1; SELECT @@ROWCOUNT AS AffectedRows', N'@0 bigint, @1 bigint', @0 = NULL, @1 = 10059
from /Users/jeremy/.rvm/gems/ruby-2.1.5@ard-checkin/gems/activerecord-sqlserver-adapter-4.2.0.pre/lib/active_record/connection_adapters/sqlserver/database_statements.rb:401:in `each'
```

**Comment by metaskills** [comment]
Thanks for reporting back. I'm having a hard time seeing that this is the adapter. This feels like a Rails bug. Have you investigated to see if this is the case? Also, why use `appointment_visitor_attributes` in your attribute list vs `appointment_visitor`? Have you tried both? Please do let me know if this is indeed an adapter issue.

**Comment by jwoertink** [comment]
I'm using `appointment_visitor_attributes` because I'm passing in params, and not the associated object. If I just use `appointment_visitor` I would get a `ActiveRecord::AssociationTypeMismatch` error. I can't say for sure if it's actually just in rails or not, but I am able to confirm that doing something similar with an app using postgres, this works. I haven't tried mysql though. 

I can create an object using this method though. So doing
```ruby
Appointment.create(directoryid: directoryid, appointment_visitor_attributes: params.merge(checkedinat: Time.current))
```
will create both appointment, and appointment_visitor objects.

**Comment by metaskills** [comment]
>  something similar with an app using postgres

Could you spin up a Rails app, make a small migration matching the minimial schema of the above models, then reproduce this to confirm? If so, I can take it from there. Thanks again!

**Comment by jwoertink** [comment]
with sqlserver? or with postgres?

**Comment by metaskills** [comment]
PostgreSQL is fine. I can then use that as a base to test and play with on SQL Server too.

**Comment by jwoertink** [comment]
Cool. I can do that. Thanks!

**Comment by metaskills** [comment]
Thanks, I appreciate it. Ping me back with a github link when ready.

**Comment by jwoertink** [comment]
Ok... so apparently this isn't an issues with this gem. Just made the new app with postgres and it does the same thing. I checked my old code which was using rails 3.2, and it works fine. This must of have been some change in rails 4, but the params have to include the id. A huge PITA, but I guess that shows me for leaving rails for a while 😝 lol. Thanks for the help! Closing this out.

**Comment by metaskills** [comment]
Thanks @jwoertink for doing that legwork! Cheers!
