### ISSUE TITLE
Conversion failed when converting the varchar value '--- !ruby/object:ActiveRecord::StatementCache::Substitute {} ' to data type int.

### ISSUE THREAD

**Issue by ginolon** [rails-sqlserver/activerecord-sqlserver-adapter#440]
I have this simple model:

```ruby
class MyThing < ActiveRecord::Base

	belongs_to :one_thing, foreign_key: "id_one"
	belongs_to :two_thing, foreign_key: "id_two"
	has_many :three_things, foreign_key: "Id_ThRee"

	establish_connection "#{Rails.env}_sqlserver".to_sym
	
	self.table_name_prefix = 'dbo.'

	self.table_name = 'MYThing'

	self.primary_key = 'Id_MyThing'

end
```
and everything is fine. Everything works.

If I change my database parameters from SQL SERVER 2012 to SQL SERVER 2014 (WITH THE SAME DATABASE restored before on 2012 and then on 2014) on server 2012 I have this error when I open a "show" action of that controller:

```
Conversion failed when converting the varchar value '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}' to data type int.

to line "@My_thing = MyThing.find(params[:id]) of My_things_controller.rb"
```

On SQL SERVER 2014 everything works fine.

What the hell is it ?

The only diference is the SQL SERVER version from 2012 to 2014. What to do?

**Comment by metaskills** [comment]
So basically if you open a `$ rails console` and type `MyThing.find(420)` the error will happen?

**Comment by metaskills** [comment]
Or does it only happen in the browser when hitting the controller action?

**Comment by ginolon** [comment]
Also in console. With command like this:

```
MyThing.find(420) I got this:
```
```
MyThing Load (187.7ms)  EXEC sp_executesql N'SELECT  [MYThing].* FROM [MYThing] WHERE [MYThing].[Id_my] = ''--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
''  ORDER BY bla bla ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
```

In SQL Server 2014 everything works good. Same database.

**Comment by metaskills** [comment]
OK. So that helps. I deleted all your controller code example since it is moot. Let's focus on the console. I have a few hunches on what may be wrong. But first, what Rails version are you using?

**Comment by ginolon** [comment]
```
gem 'rails', '4.2.5'
```

and Ruby 2.3.0.

**Comment by metaskills** [comment]
Thanks... can you show me a few more things form your console. First, I would like to see the data type of your primary key.

```ruby
MyThing.columns_hash['Id_MyThing']
```

Second, I would love to see a full stack track, not just the error. From this failing command. 

```ruby
MyThing.find(someid)
```

**Comment by ginolon** [comment]
```
MyThing.columns_hash['Id_MyThing']

=> nil
```

in rails console.

And then:

```
MyThing.find(someid)

irb(main):002:0> MyThing.find(420)
  MyThing Load (195.3ms)  EXEC sp_executesql N'SELECT  [MY].* FROM [MY] WHERE [MY].[Id_My] = ''--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
''  ORDER BY [MY].[Id_My] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
  MyThing Load (195.3ms)  EXEC sp_executesql N'SELECT  [MY].* FROM [MY] WHERE [MY].[Id_My] = ''--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
''  ORDER BY [MY].[Id_My] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
ActiveRecord::StatementInvalid: TinyTds::Error: Conversion failed when converting the varchar value '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
' to data type int.: EXEC sp_executesql N'SELECT  [MY].* FROM [MY] WHERE [MY].[Id_My] = ''--- !ruby/object:ActiveRecord::StatementCache::Substitute {}
''  ORDER BY [MY].[Id_My] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:352:in `each'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:352:in `handle_to_names_and_values_dblib'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:341:in `handle_to_names_and_values'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:316:in `_raw_select'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `block in raw_select'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
        from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `raw_select'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:260:in `sp_executesql'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-sqlserver-adapter-4.2.6/lib/active_record/connection_adapters/sqlserver/database_statements.rb:215:in `select'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:39:in `find_by_sql'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/statement_cache.rb:107:in `execute'
        from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5/lib/active_record/core.rb:153:in `find'
        from (irb):2
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
        from /app/bin/rails:4:in `require'
        from /app/bin/rails:4:in `<main>'irb(main):003:0>
```

**Comment by metaskills** [comment]
Why is this nil?

```ruby
MyThing.columns_hash['Id_MyThing']
=> nil
```

Is the real primary key you posted in your model or contrived?

**Comment by ginolon** [comment]
Yes, the primary key of that table is "Id_MyThing".

I receive that message. What to do?

**Comment by metaskills** [comment]
Show me the full `MyThing.columns` return value please.

**Comment by ginolon** [comment]
Ok, here we go:

```
MyThing.columns
  SQL (95.7ms)  USE [MY_DATABASE]
=> []
```

**Comment by metaskills** [comment]
Ah... that's the problem. The DB can not find the column objects. Can you try not setting the table prefix? Then maybe trying a different table name to maybe 'dbo.MYThing'. Make sure to restart your console each time and check to see if columns comes back non-empty.

**Comment by ginolon** [comment]
Dear @metaskills,

with or without `self.table_name_prefix = 'dbo.'` it's the same error. On Server 2014 ore another Server 2012 with same restored database everything works (with prefix).

**Comment by metaskills** [comment]
OK... for starters... I am almost 100% certain this is a permission issue. Somehow, the user you are accessing the DB can not reflect on the table. This is a table right? Or a view?

**Comment by ginolon** [comment]
Permission issue. Fixed. Thanks. (dbo was not the right scheme).
