### ISSUE TITLE
occasional timeout error

### ISSUE THREAD

**Issue by jess** [rails-sqlserver/activerecord-sqlserver-adapter#443]
I have a rails 3.1 app that uses `activerecord-sqlserver-adapter` and occasionally get this error. It seems to work fine most of the time, but then will error, and a few minutes later be fine. Hopefully this is the right place to post this. Any help would be appreciated...especially by my client :)

```
TinyTds::Error: DBPROCESS is dead or not enabled: EXEC sp_executesql N'SELECT TOP (5) [web_events].* FROM [web_events] WHERE (end_at >= ''2016-01-27 19:52:45.232'') ORDER BY start_at ASC'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:410:in `each'
```

and also related:

```
An ActiveRecord::StatementInvalid occurred in home#index:

  TinyTds::Error: Adaptive Server connection timed out: EXEC sp_executesql N'SELECT TOP (5) [web_events].* FROM [web_events] WHERE (end_at >= ''2016-01-27 19:57:14.581'') ORDER BY start_at ASC'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:410:in `each'
```

Full backtrace:

```
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:410:in `each'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:410:in `handle_to_names_and_values_dblib'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:399:in `handle_to_names_and_values'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:371:in `_raw_select'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:365:in `block in raw_select'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:244:in `block in log'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:239:in `log'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/instrumentation/active_record.rb:36:in `block in log_with_newrelic_instrumentation'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/instrumentation/active_record.rb:33:in `log_with_newrelic_instrumentation'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:365:in `raw_select'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:348:in `do_exec_query'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:24:in `exec_query'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-sqlserver-adapter-3.1.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:297:in `select'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/base.rb:470:in `find_by_sql'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/method_tracer.rb:486:in `block in find_by_sql_with_trace_ActiveRecord_self_name_find_by_sql'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/method_tracer.rb:481:in `find_by_sql_with_trace_ActiveRecord_self_name_find_by_sql'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/relation.rb:111:in `to_a'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/relation/finder_methods.rb:155:in `all'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/relation/finder_methods.rb:105:in `find'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/relation/finder_methods.rb:101:in `find'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/base.rb:441:in `find'
  app/controllers/application_controller.rb:106:in `get_upcoming_events'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:457:in `_run__3418284949968607229__process_action__300660923258329449__callbacks'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/abstract_controller/callbacks.rb:17:in `process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal/rescue.rb:17:in `process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/notifications.rb:53:in `block in instrument'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/notifications.rb:53:in `instrument'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal/params_wrapper.rb:201:in `process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:272:in `block in perform_action_with_newrelic_trace'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:267:in `perform_action_with_newrelic_trace'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/abstract_controller/base.rb:121:in `process'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/abstract_controller/rendering.rb:45:in `process'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal.rb:193:in `dispatch'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_controller/metal.rb:236:in `block in action'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/routing/route_set.rb:65:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/routing/route_set.rb:65:in `dispatch'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/routing/route_set.rb:29:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:75:in `optimized_each'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/routing/route_set.rb:531:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/rack/error_collector.rb:12:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/rack/agent_hooks.rb:18:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/rack/browser_monitoring.rb:16:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.0.83/lib/new_relic/rack/developer_mode.rb:28:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/bundler/gems/exception_notification-2eddf15f9e07/lib/exception_notification/rack.rb:28:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/galetahub-simple_captcha-0.1.3/lib/simple_captcha/middleware.rb:20:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/etag.rb:23:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/conditionalget.rb:25:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/head.rb:14:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/flash.rb:243:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/session/abstract/id.rb:195:in `context'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/session/abstract/id.rb:190:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/cookies.rb:326:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/ckeditor-3.5.0/lib/ckeditor/middleware.rb:15:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/query_cache.rb:62:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/sendfile.rb:101:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/actionpack-3.1.0/lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/railties-3.1.0/lib/rails/rack/logger.rb:13:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/methodoverride.rb:24:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/runtime.rb:17:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/activesupport-3.1.0/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-1.3.10/lib/rack/lock.rb:15:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-cache-1.0.3/lib/rack/cache/context.rb:132:in `forward'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-cache-1.0.3/lib/rack/cache/context.rb:243:in `fetch'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-cache-1.0.3/lib/rack/cache/context.rb:181:in `lookup'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-cache-1.0.3/lib/rack/cache/context.rb:65:in `call!'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-cache-1.0.3/lib/rack/cache/context.rb:50:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/railties-3.1.0/lib/rails/engine.rb:455:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/rack-canonical-host-0.0.8/lib/rack/canonical_host.rb:18:in `call'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:552:in `process_client'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:632:in `worker_loop'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:511:in `maintain_worker_count'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:277:in `join'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/bin/unicorn:126:in `<top (required)>'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `load'
  /home/deployer/apps/mssql/app/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `<main>'
```

**Comment by vin-yu** [comment]
@jess, is your application connecting to Azure SQL DB? and do you have the error number(s) being returned by the MSSQL Server?

**Comment by jess** [comment]
Hi @vin-yu , thanks so much for taking a look.

No, the db is on a standalone server in the client's office. It's MSSQL 2012. I could probably get the error number if you could hint where to retrieve it (sorry I'm not very familiar with MSSQL).

**Comment by metaskills** [comment]
@jess The source of your error may be both TinyTDS and the 3.1 version of the adapter. Please always tests the latest version of TinyTDS (with FreeTDS) when debugging this issue. Especially for a 2012 DB.

Also, we are no longer working on the 3-1-stable version of the adapter. This means that any issues reported are likely not going to get my limited time since I am putting energy to 4-2-stable and the future 5.x support. Closing this issue, but please feel free to keep discussion going as needed.
