### ISSUE TITLE
exec_rollback_db_transaction raises error when SQL-Query creates error

### ISSUE THREAD

**Issue by RobWu** [rails-sqlserver/activerecord-sqlserver-adapter#466]
https://github.com/rails-sqlserver/tiny_tds/issues/267

I try to create a new barcode.

```ruby
Barcode.create!(member_shiporder_line_id: 904577)
```
This executes:
```ruby
@connection.execute(BEGIN TRANSACTION).do
  SQL (6.5ms)  BEGIN TRANSACTION
  SQL (9.1ms)  EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577  [["membershiporderlineid", 904577]]

MY ADDED DEBUG INFO : # PUTS inside gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:187:in `rescue in within_new_transaction'
 - #<ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'barcode_postfix', table 'prod_2015_bio_membership_rhg_dev.dbo.Barcode'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577>

@connection.execute(IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION).do
  SQL (8.0ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION

ActiveRecord::StatementInvalid: TinyTds::Error: The request failed to run because the batch is aborted, this can be caused by abort signal sent from client, or another request is running in the same session, which makes the session busy.: IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:302:in `do'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:302:in `raw_connection_do'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:254:in `block in do_execute'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:254:in `do_execute'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:69:in `exec_rollback_db_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:266:in `rollback_db_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_db_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:145:in `rollback'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:187:in `rescue in within_new_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:291:in `save!'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/persistence.rb:51:in `create!'
	from (irb):7
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'2.3.0 :008 > exit
```

Looks like there is an exceptions for the ```create!``` call.. 
```
DEBUG INFO : # PUTS inside gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:187:in `rescue in within_new_transaction'

 - #<ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'barcode_postfix', table 'prod_2015_bio_membership_rhg_dev.dbo.Barcode'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577>
```

Because of this exception, ```exec_rollback_db_transaction``` will be executed, and created a new and different error (```The request failed to run because the batch is aborted...```), and hides the original error (```Cannot insert the value NULL into column```) at the same time..

**Comment by RobWu** [comment]
tiny_tds (0.7.0)

```zsh
FreeTDS: stable 0.95.80 (bottled), HEAD
Libraries to talk to Microsoft SQL Server and Sybase databases
http://www.freetds.org/
/usr/local/Cellar/FreeTDS/0.95.21 (2,817 files, 19.7M)
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/freetds.rb
==> Dependencies
Build: pkg-config ✔
Recommended: openssl ✔
Optional: unixodbc ✔
==> Options
```

**Comment by metaskills** [comment]
Hmm... can you use v0.9.5.rc.3 of TinyTDS vs 0.7.0? That is a strong version and has better support for 0.95.80

Lastly, can you use TDSVER 7.3 once you install that gem too and let me know how it goes. You can do this by setting `tds_version: 7.3` in your database.yml. I also made a PR to home-brew to update the formula to a more sane default too. See: https://github.com/Homebrew/homebrew-core/pull/504

**Comment by RobWu** [comment]
I installed sash
```zsh
➜  biografklub_app git:(master) ✗ brew install sqsh
==> Installing dependencies for sqsh: freetds
==> Installing sqsh dependency: freetds
==> Downloading https://homebrew.bintray.com/bottles/freetds-0.95.80.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring freetds-0.95.80.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/freetds/0.95.80: 2,820 files, 19.8M
==> Installing sqsh
==> Downloading https://downloads.sourceforge.net/project/sqsh/sqsh/sqsh-2.5/sqsh-2.5.16.1.tgz
==> Downloading from http://netcologne.dl.sourceforge.net/project/sqsh/sqsh/sqsh-2.5/sqsh-2.5.16.1.tgz
######################################################################## 100.0%
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/sqsh/2.5.16.1 --mandir=/usr/local/Cellar/sqsh/2.5.16.1/share/man --with-readline
==> make install
==> make install.man
🍺  /usr/local/Cellar/sqsh/2.5.16.1: 9 files, 593.2K, built in 10 seconds
```

so looks like (new) freetds-version was installed again with brew.

Afterwards it looks like it is working correct:
```ruby
Barcode.create!(membershiporderlineid: mo.id)
@connection.execute(BEGIN TRANSACTION).do
  SQL (7.0ms)  BEGIN TRANSACTION
  SQL (16.1ms)  EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577  [["membershiporderlineid", 904577]]


errors:
 - #<ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'barcode_postfix', table 'prod_2015_bio_membership_rhg_dev.dbo.Barcode'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577>

@connection.execute(IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION).do
  SQL (7.0ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'barcode_postfix', table 'prod_2015_bio_membership_rhg_dev.dbo.Barcode'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:354:in `each'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:354:in `handle_to_names_and_values_dblib'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:343:in `handle_to_names_and_values'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:318:in `_raw_select'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:313:in `block in raw_select'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:313:in `raw_select'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:261:in `sp_executesql'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:28:in `exec_insert'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/relation.rb:64:in `insert'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/persistence.rb:524:in `_create_record'
... 24 levels...
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:291:in `save!'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/persistence.rb:51:in `create!'
	from (irb):6
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
```

**Comment by metaskills** [comment]
Wait... did you do what I asked?

```
$ gem install tiny_tds -v  0.9.5.rc.3
```

Then add that version to your Gemfile?

**Comment by RobWu** [comment]
no was still with tiny_tds (0.7.0)

looks like 
==> Pouring freetds-0.95.80.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/freetds/0.95.80: 2,820 files, 19.8M

did the trick.

**Comment by metaskills** [comment]
Cool. Please do use v0.9.5.rc.3 and upward of TinyTDS tho.

**Comment by RobWu** [comment]
Will do. Thanks
