### ISSUE TITLE
Trouble with db:structure:load

### ISSUE THREAD

**Issue by johnnymo87** [rails-sqlserver/activerecord-sqlserver-adapter#503]
Hi, this gem is great! I've been using it to create and migrate a SQL server database, and that's been working fine. However, I'm having a bit of trouble with the `db:structure:load` task.

``` bash
$ rake db:drop
$ rake db:create
$ rake db:structure:load
rake aborted!
ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_handling.rb:87:in `connection'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/tasks/sqlserver_database_tasks.rb:13:in `connection'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/tasks/sqlserver_database_tasks.rb:75:in `structure_load'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:189:in `structure_load'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:222:in `load_schema_for'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:293:in `block (3 levels) in <top (required)>'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/bin/ruby_executable_hooks:15:in `eval'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:structure:load
(See full trace by running task with --trace)
```

I run `rails c`, and I see that I have no tables.
I create the following in `lib/tasks/db.rake`:

``` ruby
namespace :db do
  task :load_config do
    ActiveRecord::Base.establish_connection(
      TestPayrollApi::Application.config.database_configuration.fetch(
        'development' # refers to config/database.yml
      )
    )
  end
end
```

``` bash
$ rake db:structure:load
rake aborted!
ActiveRecord::StatementInvalid: TinyTds::Error: There is already an object named 'Client' in the database.
...< schema elided > ...
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:300[14/2909]
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `raw_
connection_do'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `bloc
k in do_execute'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `do_e
xecute'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:14:in `execu
te'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/tasks/sqlserver_database_tasks.rb:75:in `structure_load'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:189:in `structure_load'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:222:in `load_schema_for'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:293:in `block (3 levels) in <top (required)>'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/bin/ruby_executable_hooks:15:in `eval'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/bin/ruby_executable_hooks:15:in `<main>'
TinyTds::Error: There is already an object named 'Client' in the database.
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `do'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `raw_
connection_do'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `bloc
k in do_execute'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:253:in `do_e
xecute'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:14:in `execu
te'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/tasks/sqlserver_database_tasks.rb:75:in `structure_load'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:189:in `structure_load'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:222:in `load_schema_for'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-4.2.7/lib/active_record/railties/databases.rake:293:in `block (3 levels) in <top (required)>'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/bin/ruby_executable_hooks:15:in `eval'
/Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:structure:load
(See full trace by running task with --trace)
```

I run `rails c`, and I see that I have tables! I've somehow managed to half-successfully monkey-patch my way out of the problem. Even though the `db:structure:load` task throws an error, it still seems to do its job.

Any suggestions?

This is my `Gemfile.lock`:

``` ruby
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.7)
      actionpack (= 4.2.7)
      actionview (= 4.2.7)
      activejob (= 4.2.7)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7)
      actionview (= 4.2.7)
      activesupport (= 4.2.7)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.7)
      activesupport (= 4.2.7)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7)
      activesupport (= 4.2.7)
      globalid (>= 0.3.0)
    activemodel (4.2.7)
      activesupport (= 4.2.7)
      builder (~> 3.1)
    activerecord (4.2.7)
      activemodel (= 4.2.7)
      activesupport (= 4.2.7)
      arel (~> 6.0)
    activerecord-sqlserver-adapter (4.2.15)
      activerecord (~> 4.2.1)
    activesupport (4.2.7)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    builder (3.2.2)
    coderay (1.1.1)
    concurrent-ruby (1.0.2)
    diff-lcs (1.2.5)
    domain_name (0.5.20160615)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.1.1)
    dotenv-rails (2.1.1)
      dotenv (= 2.1.1)
      railties (>= 4.0, < 5.1)
    erubis (2.7.0)
    factory_girl (4.7.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.7.0)
      factory_girl (~> 4.7.0)
      railties (>= 3.0.0)
    faker (1.6.6)
      i18n (~> 0.5)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    google-protobuf (3.0.0.alpha.5.0.5.1)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    i18n (0.7.0)
    json (1.8.3)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    netrc (0.11.0)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    pkg-config (1.1.7)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7)
      actionmailer (= 4.2.7)
      actionpack (= 4.2.7)
      actionview (= 4.2.7)
      activejob (= 4.2.7)
      activemodel (= 4.2.7)
      activerecord (= 4.2.7)
      activesupport (= 4.2.7)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (4.2.7)
      actionpack (= 4.2.7)
      activesupport (= 4.2.7)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (11.2.2)
    rest-client (2.0.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.2)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    slop (3.6.0)
    spring (1.7.2)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.1.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tiny_tds (1.0.4)
      mini_portile2 (~> 2.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-sqlserver-adapter (~> 4.2)
  dotenv-rails (~> 2.1)
  factory_girl_rails (~> 4.7)
  faker (~> 1.6)
  google-protobuf (~> 3.0.0.alpha.5.0.5.1)
  pry (~> 0.10)
  rails (= 4.2.7)
  rest-client (~> 2.0)
  rspec (~> 3.5)
  rspec-rails (~> 3.5)
  spring (~> 1.7)
  tiny_tds (~> 1.0)

BUNDLED WITH
   1.12.5
```

**Comment by metaskills** [comment]
After the `db:create` task, what happens if you run `db:setup`? That's the task that loads schema/structure as needed and the higher level interface.

**Comment by johnnymo87** [comment]
OK, doing that seems to remove the need for my monkey-patch, which is great. I still hit the odd problem where it seems to try to load the schema twice, giving me `ActiveRecord::StatementInvalid: TinyTds::Error: There is already an object named 'Client' in the database.` It's strange because the migrations work smoothly (`rake db:migrate:redo STEP=9`).

Would it maybe have something to do with the fact that I'm using SQL server express? I've already noticed one quirk with this setup, where I have to open `rails dbconsole`, and do:
```sql
ALTER DATABASE [dev] SET AUTO_CLOSE OFF;
ALTER DATABASE [test] SET AUTO_CLOSE OFF;
```

**Comment by metaskills** [comment]
> Would it maybe have something to do with the fact that I'm using SQL server express?

Nah... that's not it.

> I still hit the odd problem where it seems to try to load the schema twice

Hmmm... I'd be more than willing to bet this has something to do with your environment and not the adapter... that a basic application would not load the env twice. Can you go over your gems and setup to find out what it may be?

**Comment by johnnymo87** [comment]
This is my `config/database.yml`:
```
development: &dev
  adapter: sqlserver
  database: payroll_employee_data_dev
  username: <%= ENV['MSSQL_USER'] %>
  password: <%= ENV['MSSQL_PASSWORD'] %>
  host: <%= ENV['MSSQL_HOST'] %>
test: &test
  <<: *dev
  database: payroll_employee_data_test

```
I set a debugger [`ActiveRecord::Tasks::SQLServerDatabaseTasks#structure_load`](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/tasks/sqlserver_database_tasks.rb#L74).

This is what I see:
```
From: /Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/tasks/sqlserver_database_tasks.rb @ line 75 ActiveRecord::Tasks::SQLServerDatabaseTasks#structure_load:

    74: def structure_load(filename)
 => 75:   require 'pry'; binding.pry
    76:   connection.execute File.read(filename)
    77: end

2.3.0 (#<ActiveRecord::Tasks::SQLServerDatabaseTasks:0x007fe39f452560>):0 > connection.current_database
=> "payroll_employee_data_dev"
2.3.0 (#<ActiveRecord::Tasks::SQLServerDatabaseTasks:0x007fe39f452560>):0 > configuration
=> {"adapter"=>"sqlserver",
 "database"=>"payroll_employee_data_dev",
 "username"=>"ELIDED",
 "password"=>"ELIDED",
 "host"=>"ELIDED"}
2.3.0 (#<ActiveRecord::Tasks::SQLServerDatabaseTasks:0x007fe39f452560>):0 > exit

From: /Users/jonmohrbacher/.rvm/gems/ruby-2.3.0@test-payroll/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/tasks/sqlserver_database_tasks.rb @ line 75 ActiveRecord::Tasks::SQLServerDatabaseTasks#structure_load:

    74: def structure_load(filename)
 => 75:   require 'pry'; binding.pry
    76:   connection.execute File.read(filename)
    77: end

2.3.0 (#<ActiveRecord::Tasks::SQLServerDatabaseTasks:0x007fe39f0a2c58>):0 > connection.current_database
=> "payroll_employee_data_dev"
2.3.0 (#<ActiveRecord::Tasks::SQLServerDatabaseTasks:0x007fe39f0a2c58>):0 > configuration
=> {"adapter"=>"sqlserver",
 "database"=>"payroll_employee_data_test",
 "username"=>"ELIDED",
 "password"=>"ELIDED",
 "host"=>"ELIDED"}
```

It runs `ActiveRecord::Tasks::SQLServerDatabaseTasks#structure_load` twice because I have two databases, `payroll_employee_data_dev` and `payroll_employee_data_test`. But on the second time through, it looks like `#connection` is cached from the previous run, and thus it tries to apply the schema twice to the first database.

**Comment by thomasnal** [comment]
Hi,

Thanks for reporting your issue.  It is the case on our side too.  I have just today installed this gem.  I wonder why this issue was closed without any resolution.  Please re-open the issue or provide solution description.  Thanks.

Best,
Thomas
