### ISSUE TITLE
 Rails 5: support of basic operations

### ISSUE THREAD

**Issue by marcomd** [rails-sqlserver/activerecord-sqlserver-adapter#511]
Hello,

i would give you my feedback about the rails 5 support.

Rails 5.0.0.1
tiny_tds 1.0.4
activerecord-sqlserver-adapter branch: 'rails5'
SQL Server 2012 (version 11.0.6020.0)

All the migrates are ok but when i try to insert a user:

```ruby
user = User.new email: 'admin@foo.com', password: 'dskah543', password_confirmation: 'dskah543'
user.roles  = ['admin']
user.save
```

```
TypeError: sp_executesql_sql_type can not find sql type for attr #<ActiveRecord::Relation::QueryAttribute:0x78203d0 @name="email", @value_before_type_cast="N'admin@foo.com'", @type=#<ActiveModel::Type::Value:0x7820430 @precision=nil, @scale=nil, @limit=nil>, @original_attribute=nil, @value="N'admin@foo.com'", @value_for_database="N'admin@foo.com'">
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:254:in `sp_executesql_sql_type'
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:242:in `block in sp_executesql_types_and_parameters'
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:241:in `each'
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:241:in `each_with_index'
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:241:in `sp_executesql_types_and_parameters'
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:234:in `sp_executesql'
        from ../mybundle/ruby/2.2.0/bundler/gems/activerecord-sqlserver-adapter-bec007eae766/lib/active_record/connection_adapters/sqlserver/database_statements.rb:7:in `select_rows'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:54:in `select_value'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:335:in `exists?'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/validations/uniqueness.rb:29:in `validate_each'
        from ../mybundle/ruby/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:151:in `block in validate'
        from ../mybundle/ruby/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:148:in `each'
        from ../mybundle/ruby/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:148:in `validate'
        from ../mybundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:405:in `public_send'
        from ../mybundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:405:in `block in make_lambda'
        from ../mybundle/ruby/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:150:in `call'
... 31 levels...
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:319:in `block in save'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:318:in `save'
        from ../mybundle/ruby/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:41:in `save'
        from (irb):3
        from ../mybundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
        from ../mybundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
        from ../mybundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
        from ../mybundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from ../mybundle/ruby/2.2.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'irb(main):004:0>
```

**Comment by metaskills** [comment]
Thanks! But the Rails 5 branch is not ready and un-suable. I need to find some time to pick it up. I appreciate the info, but these are known to me now till we get the base suite running against ActiveRecord (not core adapter tests). Putting energy her first. #504
