### ISSUE TITLE
StatementInvalid - Binding Error when user has no access to DB Schema

### ISSUE THREAD

**Issue by dimitertodorov** [rails-sqlserver/activerecord-sqlserver-adapter#530]
Getting the following error.

Get the following error when I try to find something. 
The same query/library works fine with JRUBY, but not with CRuby 2.3.1

```
   SQL (0.3ms)  USE [todorovDI]
  DcoDb::Esmt::Associations::DependencyAssociation Load (118.4ms)  EXEC sp_executesql N'SELECT  [BMC_CORE_BMC_Dependency].* FROM [BMC_CORE_BMC_Dependency] WHERE [BMC_CORE_BMC_Dependency].[InstanceId] = @0  ORDER BY .[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY', N'@0 nvarchar(38)', @0 = N'AGHAA5V0FUTQNAO2CM2QGU4H41EK68'  [["InstanceId", "AGHAA5V0FUTQNAO2CM2QGU4H41EK68"]]
ActiveRecord::StatementInvalid: TinyTds::Error: The multi-part identifier ".id" could not be bound.: EXEC sp_executesql N'SELECT  [BMC_CORE_BMC_Dependency].* FROM [BMC_CORE_BMC_Dependency] WHERE [BMC_CORE_BMC_Dependency].[InstanceId] = @0  ORDER BY .[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY', N'@0 nvarchar(38)', @0 = N'AGHAA5V0FUTQNAO2CM2QGU4H41EK68'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:352:in `each'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:352:in `handle_to_names_and_values_dblib'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:341:in `handle_to_names_and_values'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:316:in `_raw_select'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `block in raw_select'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `raw_select'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:260:in `sp_executesql'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:215:in `select'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:39:in `find_by_sql'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/statement_cache.rb:107:in `execute'
       	from /Users/todorovd/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/core.rb:153:in `find'
       	from (irb):1
       	from /Users/todorovd/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

I am setting self.primary_key  like this since I don't have access to the schema
```
class DcoDb::Esmt::BaseElement < DcoDb::Esmt::Base
  self.primary_key = 'Instance_Id'
  self.table_name = 'AST_BaseElement'
```

Here is the same query working fine on JRUBY
```
   (17.0ms)  USE [todorovDI]
   (6.0ms)  SELECT @@version
  DcoDb::Esmt::Associations::DependencyAssociation Load (318.0ms)  SELECT  [BMC_CORE_BMC_Dependency].* FROM [BMC_CORE_BMC_Dependency] WHERE [BMC_CORE_BMC_Dependency].[InstanceId] = N'AGHAA5V0FUTQNAO2CM2QGU4H41EK68'
=> #<DcoDb::Esmt::Associations::DependencyAssociation RequestId: "000000003078163|000000003351843", Submitter: "CURE.NARC",
```

**Comment by dimitertodorov** [comment]
Adding the following to the Model seems to work around the error.
Would be nice if this was more obvious in the errors.

```
default_scope { order(Instance_Id: :desc) }
```

**Comment by metaskills** [comment]
> I am setting self.primary_key like this since I don't have access to the schema

This issue sounds like it is permission related. The adapter needs to have full permission to the DB in some cases. Mainly when altering the schema, but in this case to reflect on it to find primary key info. Ideally setting the PK would also be used in Arel when constructing the offset/fetch SQL, but that is not the case.

Glad you found a work-around to the perm issue.
