### ISSUE TITLE
NULL-Byte makes query crash

### ISSUE THREAD

**Issue by coin3d** [rails-sqlserver/activerecord-sqlserver-adapter#544]
Dear all,

during some penetration testing, we noticed that our app crashes when the query string contains null bytes:

```
irb(main):003:0> Product.where(name: "\0")
  Product Load (0.7ms)  EXEC sp_executesql N'SELECT [products].* FROM [products] WHERE [products].[name] = @0', N'@0 nvarchar(255)', @0 = N''  [["name", "\u0000"]]
ActiveRecord::StatementInvalid: ArgumentError: string contains null byte: EXEC sp_executesql N'SELECT [products].* FROM [products] WHERE [products].[name] = @0', N'@0 nvarchar(255)', @0 = N''
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:324:in `execute'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:324:in `raw_connection_run'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:315:in `_raw_select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `block in raw_select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `raw_select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:260:in `sp_executesql'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:215:in `select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:39:in `find_by_sql'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in `exec_queries'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in `to_a'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:630:in `inspect'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Since it doesn't seem to appear with the MySQL adapter, I think it is an issue of sqlserver-adapter. We use sqlserver-adpater version 4.2.15.

Thanks for any help / advice

**Comment by metaskills** [comment]
Interesting. Recently I've been working on the Rails 5 in master and coerced this test:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/test/cases/coerced_tests.rb#L34-L35

This is the base test in Rails core. Thoughts?
https://github.com/rails/rails/blob/master/activerecord/test/cases/adapter_test.rb#L13-L25

**Comment by coin3d** [comment]
BTW, what I also discovered during testing is that single quotes vs double quotes behaves differently:
```
irb(main):013:0> Product.where(name: '\0')
  Product Load (1.5ms)  EXEC sp_executesql N'SELECT [products].* FROM [products] WHERE [products].[name] = @0', N'@0 nvarchar(255)', @0 = N'\0'  [["name", "\\0"]]
=> #<ActiveRecord::Relation []>
irb(main):014:0> Product.where(name: "\0")
  Product Load (0.2ms)  EXEC sp_executesql N'SELECT [products].* FROM [products] WHERE [products].[name] = @0', N'@0 nvarchar(255)', @0 = N''  [["name", "\u0000"]]
ActiveRecord::StatementInvalid: ArgumentError: string contains null byte: EXEC sp_executesql N'SELECT [products].* FROM [products] WHERE [products].[name] = @0', N'@0 nvarchar(255)', @0 = N''
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:324:in `execute'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:324:in `raw_connection_run'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:315:in `_raw_select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `block in raw_select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `raw_select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:260:in `sp_executesql'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/connection_adapters/sqlserver/database_statements.rb:215:in `select'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:39:in `find_by_sql'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:639:in `exec_queries'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:515:in `load'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:243:in `to_a'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:630:in `inspect'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dummy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by metaskills** [comment]
So I don't see an issue here. The DB appears to be protecting itself just like PostgreSQL. Raising an exception is not equal to "crashing the app". Exceptions happen in production and most app show the default 500 error page or even a custom one. So I am not seeing anything here that we should be doing different? Closing this issue but please do respond if you have more insights.
