### ISSUE TITLE
Environment Variables Not Working in Database.yml

### ISSUE THREAD

**Issue by roeintense** [rails-sqlserver/activerecord-sqlserver-adapter#568]
Hey bud, great work on this, love everything you do.

```
RHEL 7.2
Rails 4.1.2
ruby 2.3.3p222
```
And from the Gemfile:

```
# Gems for activerecord use with MS SQL databases
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'
```

Began a refactor on my database connections. Spun up a PG instance and loaded a different connection pool in my `config/database.yml` file, then while I was in there, decided to get important passwords into environment variables. The minute I did so, got the following:

```
TinyTds::Error (Adaptive Server connection failed (<super awesome servername redacted>)):
  tiny_tds (1.1.0) lib/tiny_tds/client.rb:53:in `connect'
  tiny_tds (1.1.0) lib/tiny_tds/client.rb:53:in `initialize'
  activerecord-sqlserver-adapter (4.1.6) lib/active_record/connection_adapters/sqlserver_adapter.rb:293:in `new'
  activerecord-sqlserver-adapter (4.1.6) lib/active_record/connection_adapters/sqlserver_adapter.rb:293:in `dblib_connect'
  activerecord-sqlserver-adapter (4.1.6) lib/active_record/connection_adapters/sqlserver_adapter.rb:282:in `connect'
  activerecord-sqlserver-adapter (4.1.6) lib/active_record/connection_adapters/sqlserver_adapter.rb:62:in `initialize'
  activerecord-sqlserver-adapter (4.1.6) lib/active_record/sqlserver_base.rb:17:in `new'
  activerecord-sqlserver-adapter (4.1.6) lib/active_record/sqlserver_base.rb:17:in `sqlserver_connection'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
  /home/gar573/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
  /home/gar573/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
  activerecord (4.1.2) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.1.2) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.1.2) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.1.2) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.1.2) lib/active_record/query_cache.rb:32:in `call'
  activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.2) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.2) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.2) lib/rails/engine.rb:514:in `call'
  railties (4.1.2) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (3.7.1) lib/puma/configuration.rb:232:in `call'
  puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
  puma (3.7.1) lib/puma/server.rb:415:in `process_client'
  puma (3.7.1) lib/puma/server.rb:275:in `block in run'
  puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

The minute I remove environment variable references, the error disappears.

Same error with Figaro.

Thanks for your attention. (Would love to help fix it!)

**Comment by metaskills** [comment]
Hmm... without seeing your database.yml and understanding how those ENV vars are set... it is hard to help. Have you tried doing something like `database: <% raise ENV.inspect %>` in your file to make sure you are indeed passing down ENV vars?

**Comment by roeintense** [comment]
Happy to provide all I can. I haven't tried `raise`. What should I look for
on a `raise`?

**Comment by metaskills** [comment]
>  What should I look for on a `raise`

The idea is you want to make sure you are indeed passing down Environment variables that you are expecting. If you can use pure YAML in your database.yml then replacing them with ERB ENV calls would pretty much indicate you are not setting those variables. Little bit outside of our control. Make sense?

**Comment by roeintense** [comment]
Plugged in ENV variables again with Figaro as a test with a `raise` call. Here's the `database.yml`:

```
default: &default                                                 
  adapter: sqlserver                                              
  pool: 5                                                         
  timeout: 60000                                                  
  encoding: utf8                                                  
                                                                  
development:                                                      
  <<: *default                                                    
  dataserver: <redacted>              
  database: <redacted>                                    
  username: <%= raise ENV['reporting_username'] %>                
  password: <%= raise ENV['reporting_password'] %>                
# Warning: The database defined as "test" will be erased and      
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.    
test:                                                             
  <<: *default                                                    
  database: db/test.sqlite3                                       
                                                                  
production:                                                       
  <<: *default                                                    
  dataserver: <redacted>              
  database: <redacted>                                    
  username: <%= raise ENV['reporting_username'] %>                
  password: <%= raise ENV['reporting_password'] %>                
```

Here's the console return:

```
[29748] ! Unable to load application: RuntimeError: Cannot load `Rails.application.database_configuration`:
<redacted>
Cannot load `Rails.application.database_configuration`:
<redacted>
```

The `<redacted>` portion  of the console return is the correct string from the `config/application.yml` file generated by Figaro.

**Comment by Chrisn27** [comment]
I'm updating a legacy app we use and there was no documentation on this in our app. How would one find where to update the target host for an entry:

defaults: &defaults
  adapter: sqlserver
  mode: odbc
  pool: 5
  timeout: 5000

All subsequent records use different tables on the default server.
