### ISSUE TITLE
Error on .group method

### ISSUE THREAD

**Issue by KitaitiMakoto** [rails-sqlserver/activerecord-sqlserver-adapter#587]
Hi,

Thank you for this great adapter! I'm working with Solidus e-commerce engine and SQL Server on Azure and it's very helpfull.

I found an error occurs when I use `.group` method:

```ruby
p User.group(:role)
# or p User.group(:role).exists?
/Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:346:in `each': T
inyTds::Error: Column 'users.id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.: SELECT [users].* FROM [users] GROUP BY [users].[r
ole] (ActiveRecord::StatementInvalid)
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:346
:in `handle_to_names_and_values_dblib'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:337
:in `handle_to_names_and_values'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:316
:in `_raw_select'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311
:in `block in raw_select'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:311:in `raw_select'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:228:in `sp_executesql'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-sqlserver-adapter-5.0.7/lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/querying.rb:39:in `find_by_sql'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:702:in `exec_queries'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:583:in `load'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:260:in `records'
        from /Users/ikeda/tmp/activerecord-sqlserver-adapter-bug/gems/ruby/2.4.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:686:in `inspect'
        from group-by.rb:33:in `p'
        from group-by.rb:33:in `<main>'
```

But when I add `#pluck` no error occurs:

```ruby
p User.group(:role).pluck(:role)
# => ["admin", "member"]
```

(Full script is here: https://gist.github.com/84a85528494f1caa07ff429d2d5b75ae )

My environment is:
(Tell me if other information is necessary.)

* OS ... OS X El Capitan
* Ruby ... v2.4.1p111
* ActiveRecord ... v5.0.2
* ActiveRecord SQL Server Adapter ... 5.0.7
* tiny_tds ... 1.3.0
* freetds ... stable 1.00.38 (bottled)(Installed via Homebrew)
* SQL Server ... [SQL Server Linux for Docker Engine][](image id: ab1edc3f85cd)

I think I should send a pull request but I cannot because I'm not good at ActiveRecord internal. So could you consider to investigate and fix this problem? Thanks.

[SQL Server Linux for Docker Engine]: https://hub.docker.com/r/microsoft/mssql-server-linux/

**Comment by metaskills** [comment]
I think this is one of those things the ORM can not solve. You have to use the right relations to get what SQL Server needs. Group is primarily in the Rails docs to support aggregations. In theory the exists should be doing that, but maybe you should use `.count > 0` instead? I do not see any code tests in core ActiveRecord that uses `group` with `exists?`. So I do think the `.count` is the way to go.

**Comment by KitaitiMakoto** [comment]
Okay, especially, I agree about `#exists?`. Thank you for reply.
