### ISSUE TITLE
ArgumentError: wrong number of arguments (0 for 1) for joins

### ISSUE THREAD

**Issue by blgrnboy** [rails-sqlserver/activerecord-sqlserver-adapter#607]
Migrating from MySQL to MSSQL, and now using activerecord-sqlserver-adapter 4.2.15.  Whenever I try to get the members or even nodes for an F5Device, I receive ArgumentError: wrong number of arguments (0 for 1).

Here is how relationships are defined:

```
class F5Device < F5Base
      has_many :nodes, :class_name => "F5Node", :foreign_key => "device_id"
      has_many :members, :through => :nodes
      has_many :group_items , :foreign_key => :device_id
      has_many :groups, :through => :group_items
      has_many :dependencies, :class_name => "Dependency", :foreign_key => :device_id
      has_many :device_applications, :class_name => "F5DeviceApplication", :foreign_key => :device_id
      has_many :applications, :through => :device_applications
      has_many :websphere_servers, :class_name => "IisDependency", :foreign_key => :f5_device_id
```

```
irb(main):003:0* f = F5Device.first
DEPRECATION WARNING: Passing a string to ActiveRecord::Base.establish_connection for a configuration lookup is deprecated, please pass a symbol (:F5_development) instead. (called from <class:F5Base> at /myApp/app/models/f5_base.rb:3)
  SQL (4.3ms)  USE [Networks]
  F5Device Load (10.8ms)  EXEC sp_executesql N'SELECT  [dbo].[f5_devices].* FROM [dbo].[f5_devices]  ORDER BY [dbo].[f5_devices].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
=> #<F5Device id: 5422, name: "MyServer", environment: "UAT", feed_type_id: 1, scm_device_id: 121764, created_at: "2012-08-23 20:02:52", updated_at: "2017-01-19 10:08:08", gonefishing: 0>
```

```
irb(main):006:0* f.nodes
/usr/local/lib/ruby/gems/2.2.0/gems/soap4r-1.5.8/lib/xsd/charset.rb:13: warning: variable $KCODE is no longer effective
/usr/local/lib/ruby/gems/2.2.0/gems/soap4r-1.5.8/lib/soap/property.rb:68: warning: encoding option is ignored - u
/usr/local/lib/ruby/gems/2.2.0/gems/soap4r-1.5.8/lib/soap/property.rb:69: warning: encoding option is ignored - u
/usr/local/lib/ruby/gems/2.2.0/gems/soap4r-1.5.8/lib/soap/property.rb:70: warning: encoding option is ignored - u
ArgumentError: wrong number of arguments (0 for 1)
        from /usr/local/lib/ruby/gems/2.2.0/gems/soap4r-1.5.8/lib/soap/property.rb:325:in `inject'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:269:in `block in constantize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:259:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:259:in `inject'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:259:in `constantize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:304:in `safe_constantize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:572:in `safe_get'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:603:in `safe_constantize'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/inheritance.rb:154:in `block in compute_type'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/inheritance.rb:153:in `each'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/inheritance.rb:153:in `compute_type'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/reflection.rb:295:in `compute_class'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/reflection.rb:291:in `klass'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/associations/association.rb:118:in `klass'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/associations/collection_association.rb:41:in `reader'
        from /usr/local/lib/ruby/gems/2.2.0/gems/activerecord-4.2.9/lib/active_record/associations/builder/association.rb:115:in `nodes'
        from (irb):6
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by metaskills** [comment]
I don't think this has anything to do with the adapter, but willing to find out. Seems to me from the stack trace... Rails/ActiveRecord is having an issue with the #nodes association... maybe around constantizing the `F5Node` string to a class. So my guess is that your issue is around where and how that class is defined.

**Comment by blgrnboy** [comment]
@metaskills You may be right.  This is coming from a non-ruby developer, just trying to "modify" the code to make it work.  Part of the problem is that we've also changed rails versions (went from 1.x to 4.x), and maybe the way that the relations are defined is outdated.  Do you have any advice

**Comment by rushed** [comment]
You might consider reverting back to a known good state and then changing only one thing at a time. When you're ready to jump Rails versions (separately from changing DBs) there are a number of guides out there and if I recall correctly most recommend handling each major version jump separately.

**Comment by blgrnboy** [comment]
Resolved.  It was actually soap4r, old legacy library that hasn't been updated in some time.
