### ISSUE TITLE
primary_Key_From_Table returns composite primary keys which get treated as one key

### ISSUE THREAD

**Issue by bf4** [rails-sqlserver/activerecord-sqlserver-adapter#719]
I'm not really sure what the fix is, so I'll describe the symptom and my resolution.

At some point I had added a `default_scope { order(primary_key => :ASC) }` to all my sql server record. I didn't recall why until I accidentally removed it, and our ci tests using `"metaskills/mssql-server-linux-rails@sha256:c00b768d0a201fcb6de3db90c1cfc468e57c913fc1369d59868f5be6e79ece17"` started failing. 

```
-- SELECT @@VERSION
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)
        Aug 22 2017 17:04:49
        Copyright (C) 2017 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 16.04.3 LTS)
```

gem versions

```
    activerecord-sqlserver-adapter (5.1.6)
    tiny_tds (2.1.2)
```

with

```
  TinyTds::Error: Invalid column name '"TicketNo", "UniqueID", "ItemNo"'.
  ... ORDER BY [Tkscale].["TicketNo", "UniqueID", "ItemNo"] ASC ....
```

i.e. the table `Tkscale` has a composite primary key on the three fields `TicketNo", "UniqueID", "ItemNo"`  which is getting executed as a single key.

Which is somewhat odd because I've defined the primary key in the record `self.primary_key = "UniqueID"`

This was getting triggered where by a `find_by` query or a `where().take(1)` and I traced it from the rails query_methods 

```
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/schema_statements.rb:142:in `primary_key'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/schema_cache.rb:41:in `primary_keys'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.1.6/lib/arel/visitors/sqlserver.rb:205:in `primary_Key_From_Table'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.1.6/lib/arel/visitors/sqlserver.rb:173:in `make_Fetch_Possible_And_Deterministic'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.1.6/lib/arel/visitors/sqlserver.rb:135:in `visit_Orders_And_Let_Fetch_Happen'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.1.6/lib/arel/visitors/sqlserver.rb:65:in `visit_Arel_Nodes_SelectStatement'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/arel-8.0.0/lib/arel/visitors/reduce.rb:14:in `visit'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/arel-8.0.0/lib/arel/visitors/reduce.rb:8:in `accept'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:33:in `select_all'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/querying.rb:39:in `find_by_sql'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/relation.rb:678:in `exec_queries'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/goldiloader-3.1.1/lib/goldiloader/active_record_patches.rb:35:in `exec_queries'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/relation.rb:546:in `load'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/relation.rb:255:in `records'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:508:in `find_take'",
 $HOME/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/relation/finder_methods.rb:100:in `take'",
```

to

`require 'active_record/connection_adapters/sqlserver/schema_statements'`

```ruby
def primary_keys(table_name)
  primaries = primary_keys_select(table_name)
  primaries.present? ? primaries : identity_columns(table_name).map(&:name)
end
```

as used by

`require 'arel/visitors/sqlserver'`

```ruby
      def primary_Key_From_Table t
        return unless t
        column_name = @connection.schema_cache.primary_keys(t.name) ||
          @connection.schema_cache.columns_hash(t.name).first.try(:second).try(:name)
        column_name ? t[column_name] : nil
      end
```

and was able to resolve by just patching the `primary_Key_From_Table` and leaving the `connection.schema_cache.primary_key` alone

i.e.

```diff
require 'arel/visitors/sqlserver'
module Arel
  module Visitors
    class SQLServer < Arel::Visitors::ToSql
      private

      def primary_Key_From_Table t
        return unless t
+        #
+        # NOTE(BF): Always use the schema_cache.primary_key(table_name) to be get one key
+        # else we get generated sql with invalid order clauses
+        #   TinyTds::Error: Invalid column name '"TicketNo", "UniqueID", "ItemNo"'.
+        #   ... ORDER BY [Tkscale].["TicketNo", "UniqueID", "ItemNo"] ASC ....
+        #
-        column_name = @connection.schema_cache.primary_keys(t.name) ||
+        column_name = @connection.schema_cache.primary_keys(t.name).try(:first) ||
          @connection.schema_cache.columns_hash(t.name).first.try(:second).try(:name)
        column_name ? t[column_name] : nil
      end
    end
  end
end
```

but that interacted poorly with table without a composite primary key, since it got the first character in the key name, (from pk.first), so instead, I patched `module ActiveRecord::ConnectionAdapters::SQLServer::SchemaStatements` or add to it `primary_key` with the diff below as compared to the ar schema statement

```diff
        def primary_key(table_name)
          pk = primary_keys(table_name)
+          pk = suppress_composite_primary_key(pk, table_name)
          pk = pk.first unless pk.size > 1
          pk
        end

+        # per https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/attribute_methods/primary_key.rb#L130-L137
+        def suppress_composite_primary_key(pk, table_name)
+          return pk unless pk.size > 1
+
+          ActiveRecord::Base.logger.debug do
+            <<-WARNING.strip_heredoc
+            WARNING: Active Record does not support composite primary key.
+              #{table_name} has composite primary key. Composite primary key is ignored.
+              WARNING
+          end
+          pk[0..0]
+        end
```

**Comment by wpolicarpo** [comment]
This is similar to #757 

I would like to spend some time investigating the side-effects of the proposed change. Give me some time and I will get back to you @bf4.
