### ISSUE TITLE
bundle exec rake db:create causing "TinyTds::Error: Database 'blog_test' does not exist. Make sure that the name is entered correctly."

### ISSUE THREAD

**Issue by ganeshkumar** [rails-sqlserver/activerecord-sqlserver-adapter#837]
## Issue
running bundle exec rake db:create causing "TinyTds::Error: Database 'blog_test' does not exist. Make sure that the name is entered correctly."

## Expected behavior
it should create the db without errors

## Actual behavior
getting an error TinyTds::Error: Database 'blog_test' does not exist. Make sure that the name is entered correctly.

## How to reproduce

```
require "bundler/inline"

 gemfile(true) do
  source "https://rubygems.org"
  gem "tiny_tds"
  gem "activerecord", "5.2.4.3"
  gem "activerecord-sqlserver-adapter", "5.2.1"
end`

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter:  "sqlserver",
  timeout:  5000,
  pool:     100,
  encoding: "utf8",
  database: "blog_test",
  username: "sa",
  password: "ur_password",
  host:     "localhost",
  port:     1433,
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  drop_table :bug_tests rescue nil

  create_table :bug_tests, force: true do |t|
    t.bigint :external_id
  end
end

class BugTest < ActiveRecord::Base
end

class TestBugTest < Minitest::Test
  def setup
    @bug_test = BugTest.create!(external_id: 2_032_070_100_001)
  end

  def test_count
    assert_equal 1, BugTest.count
  end
end

```

**OutPut:**
------------------

```
Traceback (most recent call last):
	27: from test_script.rb:27:in `<main>'
	26: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:46:in `define'
	25: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:50:in `define'
	24: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/schema.rb:50:in `instance_eval'
	23: from test_script.rb:30:in `block in <main>'
	22: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:860:in `method_missing'
	21: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:840:in `say_with_time'
	20: from /usr/local/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:840:in `block in say_with_time'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:861:in `block in method_missing'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/migration.rb:854:in `connection'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_handling.rb:90:in `connection'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.2.1/lib/active_record/sqlserver_base.rb:13:in `sqlserver_connection'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.2.1/lib/active_record/sqlserver_base.rb:13:in `new'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.2.1/lib/active_record/connection_adapters/sqlserver_adapter.rb:64:in `initialize'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.2.1/lib/active_record/connection_adapters/sqlserver_adapter.rb:365:in `connect'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.2.1/lib/active_record/connection_adapters/sqlserver_adapter.rb:379:in `dblib_connect'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/activerecord-sqlserver-adapter-5.2.1/lib/active_record/connection_adapters/sqlserver_adapter.rb:379:in `new'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/tiny_tds-2.1.2/lib/tiny_tds/client.rb:60:in `initialize'
/usr/local/lib/ruby/gems/2.6.0/gems/tiny_tds-2.1.2/lib/tiny_tds/client.rb:60:in `connect': Database 'blog_test' does not exist. Make sure that the name is entered correctly. (TinyTds::Error)
```

## Details

- **Rails version**: `5.2.4.3`
- **SQL Server adapter version**: `5.2.1`
- **TinyTDS version**: `2.1.2`

**Comment by ganeshkumar** [comment]
Sorry my mistake please ignore
